spring:
  rabbitmq:
    host: srv-ceesp.proj.ufsm.br
    port: 8082
    username: guest
    password: guest
  datasource:
    url: jdbc:postgresql://localhost:5432/pilacoin
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

queue:
  pila:
    minerado: pila-minerado
    validado: pila-validado
    transferir: transferir-pila
  bloco:
    descobre: descobre-bloco
    minerado: bloco-minerado
    validado: bloco-validado
  msgs: clients-msgs
  errors: clients-errors
  dificuldade: dificuldade

pilacoin:
  home: ../pilacoin
  username: londero.edu